[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# No need for custom redirects with the Next.js plugin, but keeping a fallback
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404 